### ISSUE TITLE
error: UnityGfxDeviceWorker(13): EXC_BAD_ACCESS......

### ISSUE THREAD

**Issue by xh4010** [keyv/iOSUnityVuforiaGuide#8]
Thank you very much, according to your approach successful unity app embedded ios project, build success, but crash  at the beginning of vuforia recognition, do not see the camera image.

my development environment:
OS X EI capitan, Xcode 7.3.1, Unity 5.4.0f3, Vuforia 6.0

I do not know where the problem lies, need your help, thanks.

![image](http://weixin.artron.com.cn/app/artronYuntu/error/error.png)

artronyuntu`AddCreatedTexture:
    0x100ccdad0 <+0>:   stp    x24, x23, [sp, #-64]!
    0x100ccdad4 <+4>:   stp    x22, x21, [sp, #16]
    0x100ccdad8 <+8>:   stp    x20, x19, [sp, #32]
    0x100ccdadc <+12>:  stp    x29, x30, [sp, #48]
    0x100ccdae0 <+16>:  add    x29, sp, #48              ; =48 
    0x100ccdae4 <+20>:  sub    sp, sp, #160              ; =160 
    0x100ccdae8 <+24>:  mov    x22, x2
    0x100ccdaec <+28>:  mov    x21, x1
    0x100ccdaf0 <+32>:  mov    x20, x0
    0x100ccdaf4 <+36>:  mov    x0, x21
    0x100ccdaf8 <+40>:  bl     0x1018be3fc               ; symbol stub for: objc_retain
    0x100ccdafc <+44>:  mov    x19, x0
    0x100ccdb00 <+48>:  str    w20, [sp, #48]
    0x100ccdb04 <+52>:  adrp   x24, 4244
    0x100ccdb08 <+56>:  add    x24, x24, #3832           ; =3832 
    0x100ccdb0c <+60>:  ldr    x0, [x24]
    0x100ccdb10 <+64>:  add    x8, sp, #24               ; =24 
    0x100ccdb14 <+68>:  add    x1, sp, #48               ; =48 
    0x100ccdb18 <+72>:  bl     0x100c5faa8               ; find at densehashtable.h:698
    0x100ccdb1c <+76>:  ldr    x8, [x24]
    0x100ccdb20 <+80>:  ldp    x9, x10, [x8, #56]
    0x100ccdb24 <+84>:  add    x9, x9, x10, lsl #4
    0x100ccdb28 <+88>:  stp    x8, x9, [sp]
    0x100ccdb2c <+92>:  str    x9, [sp, #16]
    0x100ccdb30 <+96>:  mov    x0, sp
    0x100ccdb34 <+100>: bl     0x100c5fc28               ; advance_past_empty_and_deleted at densehashtable.h:153
    0x100ccdb38 <+104>: ldr    x8, [sp, #32]
    0x100ccdb3c <+108>: ldr    x9, [sp, #8]
    0x100ccdb40 <+112>: cmp    x8, x9
    0x100ccdb44 <+116>: b.eq   0x100ccdb50               ; <+128> at TexturesMetal.mm:218
    0x100ccdb48 <+120>: ldr    x0, [x8, #8]
    0x100ccdb4c <+124>: b      0x100ccdb54               ; <+132> at TexturesMetal.mm:219
    0x100ccdb50 <+128>: movz   x0, #0
    0x100ccdb54 <+132>: cbz    x0, 0x100ccdb64           ; <+148> at TexturesMetal.mm:222
    0x100ccdb58 <+136>: mov    x1, x21
    0x100ccdb5c <+140>: bl     0x1018be444               ; symbol stub for: objc_storeStrong
    0x100ccdb60 <+144>: b      0x100ccdc04               ; <+308> at TexturesMetal.mm:223
    0x100ccdb64 <+148>: mov    x0, x19
    0x100ccdb68 <+152>: bl     0x1018be3fc               ; symbol stub for: objc_retain
    0x100ccdb6c <+156>: mov    x21, x0
    0x100ccdb70 <+160>: adrp   x8, 4561
    0x100ccdb74 <+164>: ldr    x0, [x8, #1936]
    0x100ccdb78 <+168>: bl     0x100ccedf8               ; alloc at FixedSizeAllocator.h:199
    0x100ccdb7c <+172>: mov    x23, x0
    0x100ccdb80 <+176>: stp    x21, xzr, [x23]
    0x100ccdb84 <+180>: cbz    w22, 0x100ccdb90          ; <+192> at TexturesMetal.mm:222
    0x100ccdb88 <+184>: orr    w8, wzr, #0x2
    0x100ccdb8c <+188>: strb   w8, [x23, #15]
    0x100ccdb90 <+192>: stur   w20, [x29, #-56]
    0x100ccdb94 <+196>: ldr    x0, [x24]
    0x100ccdb98 <+200>: sub    x8, x29, #80              ; =80 
    0x100ccdb9c <+204>: sub    x1, x29, #56              ; =56 
    0x100ccdba0 <+208>: bl     0x100c5faa8               ; find at densehashtable.h:698
    0x100ccdba4 <+212>: ldr    x8, [x24]
    0x100ccdba8 <+216>: ldp    x9, x10, [x8, #56]
    0x100ccdbac <+220>: add    x9, x9, x10, lsl #4
    0x100ccdbb0 <+224>: stp    x8, x9, [sp, #104]
    0x100ccdbb4 <+228>: str    x9, [sp, #120]
    0x100ccdbb8 <+232>: add    x0, sp, #104              ; =104 
    0x100ccdbbc <+236>: bl     0x100c5fc28               ; advance_past_empty_and_deleted at densehashtable.h:153
    0x100ccdbc0 <+240>: ldur   x8, [x29, #-72]
    0x100ccdbc4 <+244>: ldr    x9, [sp, #112]
    0x100ccdbc8 <+248>: cmp    x8, x9
    0x100ccdbcc <+252>: b.eq   0x100ccdbd8               ; <+264> [inlined] UpdateTexture + 68 at TexturesMetal.mm:222
    0x100ccdbd0 <+256>: str    x23, [x8, #8]
    0x100ccdbd4 <+260>: b      0x100ccdc04               ; <+308> at TexturesMetal.mm:223
    0x100ccdbd8 <+264>: ldr    x22, [x24]
    0x100ccdbdc <+268>: str    w20, [sp, #88]
    0x100ccdbe0 <+272>: str    x23, [sp, #96]
    0x100ccdbe4 <+276>: orr    w1, wzr, #0x1
    0x100ccdbe8 <+280>: mov    x0, x22
    0x100ccdbec <+284>: movz   x2, #0
    0x100ccdbf0 <+288>: bl     0x100c5fc78               ; resize_delta at densehashtable.h:455
    0x100ccdbf4 <+292>: add    x8, sp, #56               ; =56 
    0x100ccdbf8 <+296>: add    x1, sp, #88               ; =88 
    0x100ccdbfc <+300>: mov    x0, x22
    0x100ccdc00 <+304>: bl     0x100c5fd94               ; insert_noresize at densehashtable.h:736
    0x100ccdc04 <+308>: mov    x0, x19
    0x100ccdc08 <+312>: sub    sp, x29, #48              ; =48 
    0x100ccdc0c <+316>: ldp    x29, x30, [sp, #48]
    0x100ccdc10 <+320>: ldp    x20, x19, [sp, #32]
    0x100ccdc14 <+324>: ldp    x22, x21, [sp, #16]
    0x100ccdc18 <+328>: ldp    x24, x23, [sp], #64
    0x100ccdc1c <+332>: b      0x1018be3f0               ; symbol stub for: objc_release
    0x100ccdc20 <+336>: mov    x19, x0
    0x100ccdc24 <+340>: mov    x0, x21
    0x100ccdc28 <+344>: bl     0x1018be3f0               ; symbol stub for: objc_release
    0x100ccdc2c <+348>: b      0x100ccdc34               ; <+356> at TexturesMetal.mm:223
    0x100ccdc30 <+352>: mov    x19, x0
    0x100ccdc34 <+356>: mov    x0, x21
    0x100ccdc38 <+360>: bl     0x1018be3f0               ; symbol stub for: objc_release
    0x100ccdc3c <+364>: mov    x0, x19
    0x100ccdc40 <+368>: bl     0x1018bc8f0               ; symbol stub for: _Unwind_Resume

debug log:
2016-09-07 14:30:24.706 artronyuntu[1008:312120] -> registered mono modules 0x101b084b4
-> applicationDidFinishLaunching()
2016-09-07 14:30:24.982 artronyuntu[1008:312120] 1111111
-> applicationDidBecomeActive()
GfxDevice: creating device client; threaded=1
Init: screen size 750x1334
Initializing Metal device caps: Apple A9 GPU
Initialize engine version: 5.4.0f3 (a6d8d714de6f)
OnLevelWasLoaded was found on WebCamBehaviour
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.UI.ObjectPool`1:Release(T)
System.Text.RegularExpressions.LinkRef:.ctor()

[ line 375](Filename:  Line: 375)

OnLevelWasLoaded was found on KeepAliveBehaviour
This message has been deprecated and will be removed in a later version of Unity.
Add a delegate to SceneManager.sceneLoaded instead to get notifications after scene loading has completed
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.UI.ObjectPool`1:Release(T)
System.Text.RegularExpressions.LinkRef:.ctor()

[ line 375](Filename:  Line: 375)

UnloadTime: 0.900083 ms
Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 6.557000 ms

Unloading 6 unused Assets to reduce memory usage. Loaded Objects now: 276.
Total: 0.292791 ms (FindLiveObjects: 0.019208 ms CreateObjectMapping: 0.010041 ms MarkObjects: 0.248958 ms  DeleteObjects: 0.014041 ms)

Starttt
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
AboutScreen:OnStartAR()
UnityEngine.Events.UnityAction:Invoke()
UnityEngine.Events.InvokableCall:Invoke(Object[])
UnityEngine.Graphics:SetRenderTarget(RenderBuffer, RenderBuffer)
UnityEngine.Events.InvokableCallList:Invoke(Object[])
UnityEngine.Events.UnityEventBase:Invoke(Object[])
UnityEngine.Events.UnityEvent:Invoke()
UnityEngine.UI.Button:Press()
UnityEngine.UI.Button:OnPointerClick(PointerEventData)
UnityEngine.UI.Mask:GetModifiedMaterial(Material)
UnityEngine.EventSystems.ExecuteEvents:Execute(IPointerClickHandler, BaseEventData)
UnityEngine.EventSystems.EventFunction`1:Invoke(T1, BaseEventData)
UnityEngine.EventSystems.ExecuteEvents:Execute(GameObject, BaseEventData, EventFunction`1)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchPress(PointerEventData, Boolean, Boolean)
UnityEngine.EventSystems.StandaloneInputModule:ProcessTouchEvents()
UnityEngine.EventSystems.StandaloneInputModule:Process()
System.Security.Cryptography.MACTripleDES:HashFinal()
UnityEngine.EventSystems.EventSystem:Update()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Unloading 3 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 1.612333 ms

Unloading 8 unused Assets to reduce memory usage. Loaded Objects now: 241.
Total: 0.317083 ms (FindLiveObjects: 0.018666 ms CreateObjectMapping: 0.011541 ms MarkObjects: 0.263750 ms  DeleteObjects: 0.022416 ms)

Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
UnloadTime: 1.619250 ms
Setting BehaviourComponentFactory
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.ComponentFactoryStarterBehaviour:SetBehaviourComponentFactory()
System.Action:Invoke()
Vuforia.ComponentFactoryStarterBehaviour:Awake()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.GameObject:Internal_AddComponentWithType(Type)
UnityEngine.GameObject:AddComponent(Type)
UnityEngine.GameObject:AddComponent()
Vuforia.VuforiaBehaviour:Awake()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Trackable stones lost
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.DefaultTrackableEventHandler:OnTrackingLost()
Vuforia.DefaultTrackableEventHandler:OnTrackableStateChanged(Status, Status)
System.Comparison`1:EndInvoke(IAsyncResult)
Vuforia.TrackableBehaviour:RegisterTrackableEventHandler(ITrackableEventHandler)
Vuforia.DefaultTrackableEventHandler:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Trackable chips lost
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.DefaultTrackableEventHandler:OnTrackingLost()
Vuforia.DefaultTrackableEventHandler:OnTrackableStateChanged(Status, Status)
System.Comparison`1:EndInvoke(IAsyncResult)
Vuforia.TrackableBehaviour:RegisterTrackableEventHandler(ITrackableEventHandler)
Vuforia.DefaultTrackableEventHandler:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Trackable tarmac lost
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.DefaultTrackableEventHandler:OnTrackingLost()
Vuforia.DefaultTrackableEventHandler:OnTrackableStateChanged(Status, Status)
System.Comparison`1:EndInvoke(IAsyncResult)
Vuforia.TrackableBehaviour:RegisterTrackableEventHandler(ITrackableEventHandler)
Vuforia.DefaultTrackableEventHandler:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Initializing Vuforia...
2016-09-07 14:30:36.354 artronyuntu[1008:312120] INFO/AR(1008) 2016-09-08 14:30:36: Vuforia SDK version 6.0.114
2016-09-07 14:30:36.427 artronyuntu[1008:312120] Rendering mode set to: OpenGL ES 2.0
2016-09-07 14:30:36.449 artronyuntu[1008:312120] Rendering mode set to: OpenGL ES 2.0
Vuforia initialization successful
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.VuforiaAbstractBehaviour:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

SetHint
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.VuforiaUnityImpl:SetHint(VuforiaHint, Int32)
Vuforia.VuforiaUnity:SetHint(VuforiaHint, Int32)
Vuforia.VuforiaAbstractBehaviour:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

SetHint
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.VuforiaUnityImpl:SetHint(VuforiaHint, Int32)
Vuforia.VuforiaUnity:SetHint(VuforiaHint, Int32)
Vuforia.VuforiaAbstractBehaviour:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

SetHint
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.VuforiaUnityImpl:SetHint(VuforiaHint, Int32)
Vuforia.VuforiaUnity:SetHint(VuforiaHint, Int32)
Vuforia.VuforiaAbstractBehaviour:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

2016-09-07 14:30:36.492 artronyuntu[1008:312120] ERROR/AR(1008) 2016-09-08 14:30:36: CameraDevice::getCameraCalibration(): Failed to get camera calibration because the camera is not initialized.
2016-09-07 14:30:36.495 artronyuntu[1008:312120] INFO/AR(1008) 2016-09-08 14:30:36: ObjectTracker: Successfully created dataset
Successfully created data set.
Found Trackable named stones with id 1
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.StateManagerImpl:AssociateTrackableBehavioursForDataSet(DataSet)
Vuforia.DataSetImpl:Load(String, StorageType)
Vuforia.WordResultImpl:get_CurrentStatus()
Vuforia.DataSetImpl:Load(String)
Vuforia.ReconstructionAbstractBehaviour:.ctor()
Vuforia.DatabaseLoadAbstractBehaviour:LoadDatasets()
Vuforia.VuforiaAbstractBehaviour:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Found Trackable named chips with id 2
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.StateManagerImpl:AssociateTrackableBehavioursForDataSet(DataSet)
Vuforia.DataSetImpl:Load(String, StorageType)
Vuforia.WordResultImpl:get_CurrentStatus()
Vuforia.DataSetImpl:Load(String)
Vuforia.ReconstructionAbstractBehaviour:.ctor()
Vuforia.DatabaseLoadAbstractBehaviour:LoadDatasets()
Vuforia.VuforiaAbstractBehaviour:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

2016-09-07 14:30:36.546 artronyuntu[1008:312120] INFO/AR(1008) 2016-09-08 14:30:36: ObjectTracker: Successfully created dataset
Successfully created data set.
Found Trackable named tarmac with id 4
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.StateManagerImpl:AssociateTrackableBehavioursForDataSet(DataSet)
Vuforia.DataSetImpl:Load(String, StorageType)
Vuforia.WordResultImpl:get_CurrentStatus()
Vuforia.DataSetImpl:Load(String)
Vuforia.ReconstructionAbstractBehaviour:.ctor()
Vuforia.DatabaseLoadAbstractBehaviour:LoadDatasets()
Vuforia.VuforiaAbstractBehaviour:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

StartVuforia
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.VuforiaAbstractBehaviour:StartVuforia(Boolean, Boolean)
Vuforia.VuforiaAbstractBehaviour:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

cameraDeviceStartCamera
2016-09-07 14:30:36.580 artronyuntu[1008:312227] DEBUG/AR(1008) Could not find a UIView with CAEAGLLayer or CAMetalLayer layer class that responds to selector renderFrameVuforia
2016-09-07 14:30:36.581 artronyuntu[1008:312227] DEBUG/AR(1008) UIView has CAMetalLayer layer class
2016-09-07 14:30:36.581 artronyuntu[1008:312227] DEBUG/AR(1008) UIView does not respond to selector renderFrameVuforia
2016-09-07 14:30:36.581 artronyuntu[1008:312227] DEBUG/AR(1008) UIView has CAMetalLayer layer class
2016-09-07 14:30:36.581 artronyuntu[1008:312227] DEBUG/AR(1008) UIView does not respond to selector renderFrameVuforia
2016-09-07 14:30:36.581 artronyuntu[1008:312227] DEBUG/AR(1008) Could not find a UIView with CAEAGLLayer or CAMetalLayer layer class that responds to selector renderFrameVuforia
2016-09-07 14:30:36.581 artronyuntu[1008:312227] DEBUG/AR(1008) Could not find a UIView with CAEAGLLayer or CAMetalLayer layer class that responds to selector renderFrameVuforia
2016-09-07 14:30:36.738 artronyuntu[1008:312198] Deleting old image data @ 0x0
2016-09-07 14:30:36.738 artronyuntu[1008:312198] Created new image data buffer @ 0x10fbb8000 w/ 3110400 bytes
Creating a Mono Camera Configuration (Check for reflection)
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.DigitalEyewearAbstractBehaviour:ConfigureView()
Vuforia.DigitalEyewearAbstractBehaviour:OnVuforiaStarted()
System.Action:Invoke()
System.Action:Invoke()
System.Action:Invoke()
Vuforia.VuforiaAbstractBehaviour:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()

Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

2016-09-07 14:30:36.746 artronyuntu[1008:312120] ERROR/AR(1008) 2016-09-08 14:30:36: VideoBackgroundConfig with screen size of zero received, skipping config step
Requested Focus mode FOCUS_MODE_CONTINUOUSAUTO successfully.
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.CameraDeviceImpl:SetFocusMode(FocusMode)
Vuforia.ReconstructionAbstractBehaviour:.ctor()
CameraSettings:SwitchAutofocus(Boolean)
CameraSettings:OnVuforiaStarted()
System.Action:Invoke()
Vuforia.VuforiaAbstractBehaviour:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Successfully enabled continuous autofocus.
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
CameraSettings:SwitchAutofocus(Boolean)
CameraSettings:OnVuforiaStarted()
System.Action:Invoke()
Vuforia.VuforiaAbstractBehaviour:Start()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Trackable stones lost
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.DefaultTrackableEventHandler:OnTrackingLost()
Vuforia.DefaultTrackableEventHandler:OnTrackableStateChanged(Status, Status)
System.Comparison`1:EndInvoke(IAsyncResult)
Vuforia.TrackableBehaviour:OnTrackerUpdate(Status)
Vuforia.DataSetTrackableBehaviour:OnTrackerUpdate(Status)
System.Security.Cryptography.MACTripleDES:HashFinal()
Vuforia.StateManagerImpl:UpdateTrackablePoses(Transform, TrackableResultData[], VuMarkTargetResultData[], IdPair, Int32)
Vuforia.VuforiaManagerImpl:UpdateTrackers(FrameState)
Vuforia.VuforiaManagerImpl:Update(ScreenOrientation, Boolean)
Vuforia.VuforiaAbstractBehaviour:UpdateStatePrivate(Boolean, Boolean)
Vuforia.VuforiaAbstractBehaviour:UpdateState(Boolean, Boolean)
Vuforia.DigitalEyewearAbstractBehaviour:Update()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Trackable chips lost
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.DefaultTrackableEventHandler:OnTrackingLost()
Vuforia.DefaultTrackableEventHandler:OnTrackableStateChanged(Status, Status)
System.Comparison`1:EndInvoke(IAsyncResult)
Vuforia.TrackableBehaviour:OnTrackerUpdate(Status)
Vuforia.DataSetTrackableBehaviour:OnTrackerUpdate(Status)
System.Security.Cryptography.MACTripleDES:HashFinal()
Vuforia.StateManagerImpl:UpdateTrackablePoses(Transform, TrackableResultData[], VuMarkTargetResultData[], IdPair, Int32)
Vuforia.VuforiaManagerImpl:UpdateTrackers(FrameState)
Vuforia.VuforiaManagerImpl:Update(ScreenOrientation, Boolean)
Vuforia.VuforiaAbstractBehaviour:UpdateStatePrivate(Boolean, Boolean)
Vuforia.VuforiaAbstractBehaviour:UpdateState(Boolean, Boolean)
Vuforia.DigitalEyewearAbstractBehaviour:Update()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Trackable tarmac lost
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
UnityEngine.DebugLogHandler:Internal_Log(LogType, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Renderer:get_sortingOrder()
UnityEngine.Logger:Log(LogType, Object)
System.UriParser:InternalRegister(Hashtable, UriParser, String, Int32)
UnityEngine.Debug:Log(Object)
Vuforia.DefaultTrackableEventHandler:OnTrackingLost()
Vuforia.DefaultTrackableEventHandler:OnTrackableStateChanged(Status, Status)
System.Comparison`1:EndInvoke(IAsyncResult)
Vuforia.TrackableBehaviour:OnTrackerUpdate(Status)
Vuforia.DataSetTrackableBehaviour:OnTrackerUpdate(Status)
System.Security.Cryptography.MACTripleDES:HashFinal()
Vuforia.StateManagerImpl:UpdateTrackablePoses(Transform, TrackableResultData[], VuMarkTargetResultData[], IdPair, Int32)
Vuforia.VuforiaManagerImpl:UpdateTrackers(FrameState)
Vuforia.VuforiaManagerImpl:Update(ScreenOrientation, Boolean)
Vuforia.VuforiaAbstractBehaviour:UpdateStatePrivate(Boolean, Boolean)
Vuforia.VuforiaAbstractBehaviour:UpdateState(Boolean, Boolean)
Vuforia.DigitalEyewearAbstractBehaviour:Update()
Mono.Security.X509.Extensions.BasicConstraintsExtension:ToString()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
Vuforia.TrackerManager:DeinitTracker()
System.Text.RegularExpressions.LinkRef:.ctor()

(Filename: /Users/builduser/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)

Unloading 12 unused Assets to reduce memory usage. Loaded Objects now: 619.
Total: 0.828875 ms (FindLiveObjects: 0.046625 ms CreateObjectMapping: 0.016708 ms MarkObjects: 0.721333 ms  DeleteObjects: 0.043458 ms)

(lldb)

**Comment by jacobokoenig** [comment]
+1
My console marks Using OpenGL ES graphics, and crashes with no reason (lldb)

**Comment by mixx85** [comment]
I have the same problem!
you found a solution?

**Comment by JackQian12** [comment]
+1 reall need a solution

**Comment by jacobokoenig** [comment]
I went through a lot of errors that I solved in different ways, If I am not mistaken, this one I solved by including Camera permissions in the plist.info file.

Key       :  Privacy - Camera Usage Description  
Value     :  $(PRODUCT_NAME) camera use [Or whatever other description you want]

Let me know if this works.

**Comment by ropinheiro** [comment]
Hello, I have this same problem, I reported full details here:

https://forum.unity.com/threads/vuforia-augmented-reality-black-screen-when-accessing-android-camera.265335/#post-3673327

and here:

https://forum.unity.com/threads/vuforia-augmented-reality-black-screen-when-accessing-android-camera.265335/#post-3673429

But I still continue with problems.

@jacobo360, what do you mean with: 

> I went through a lot of errors that I solved in different ways, If I am not mistaken, this one I solved by including Camera permissions in the plist.info file.
> 
> Key : Privacy - Camera Usage Description
> Value : $(PRODUCT_NAME) camera use [Or whatever other description you want]
> 
> Let me know if this works.

I opened my plist.info file and I don't know how to fit what you said in the file. The format seems a lot different:

> <xml>
    <plist version="1.0">
      <dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>abci</string>
	<key>CFBundleGetInfoString</key>
	<string></string>
	<key>CFBundleIconFile</key>
	<string></string>
	<key>CFBundleIdentifier</key>
	<string></string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleLongVersionString</key>
	<string></string>
	<key>CFBundleName</key>
	<string></string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string></string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string></string>
	<key>CSResourcesFileMapped</key>
	<true/>
	<key>NSHumanReadableCopyright</key>
	<string></string>
      </dict>
    </plist>
  </xml>
